#!/bin/bash
./test/run_plots.sh test/sampleLists/signal_and_stack/POGTightID/plots_Bkg_e_2016.txt 3 LocalJob_sigstack_e_2016.out
./test/run_plots.sh test/sampleLists/signal_and_stack/POGTightID/plots_Bkg_e_2017.txt 3 LocalJob_sigstack_e_2017.out
./test/run_plots.sh test/sampleLists/signal_and_stack/POGTightID/plots_Bkg_e_2018.txt 3 LocalJob_sigstack_e_2018.out
./test/run_plots.sh test/sampleLists/signal_and_stack/POGTightID/plots_Bkg_m_2016.txt 3 LocalJob_sigstack_m_2016.out
./test/run_plots.sh test/sampleLists/signal_and_stack/POGTightID/plots_Bkg_m_2017.txt 3 LocalJob_sigstack_m_2017.out
./test/run_plots.sh test/sampleLists/signal_and_stack/POGTightID/plots_Bkg_m_2018.txt 3 LocalJob_sigstack_m_2018.out
./test/run_plots.sh test/sampleLists/signal_and_stack/POGTightID_unparametrized/plots_Bkg_e_2016.txt 3 LocalJob_sigstack_e_2016_unp.out
./test/run_plots.sh test/sampleLists/signal_and_stack/POGTightID_unparametrized/plots_Bkg_e_2017.txt 3 LocalJob_sigstack_e_2017_unp.out
./test/run_plots.sh test/sampleLists/signal_and_stack/POGTightID_unparametrized/plots_Bkg_e_2018.txt 3 LocalJob_sigstack_e_2018_unp.out
./test/run_plots.sh test/sampleLists/signal_and_stack/POGTightID_unparametrized/plots_Bkg_m_2016.txt 3 LocalJob_sigstack_m_2016_unp.out
./test/run_plots.sh test/sampleLists/signal_and_stack/POGTightID_unparametrized/plots_Bkg_m_2017.txt 3 LocalJob_sigstack_m_2017_unp.out
./test/run_plots.sh test/sampleLists/signal_and_stack/POGTightID_unparametrized/plots_Bkg_m_2018.txt 3 LocalJob_sigstack_m_2018_unp.out
./test/run_plots.sh test/sampleLists/signal_and_stack/POGTightID_unparametrized_LowAndHighMass/plots_Bkg_e_2016.txt 3 LocalJob_sigstack_e_2016_unp2.out
./test/run_plots.sh test/sampleLists/signal_and_stack/POGTightID_unparametrized_LowAndHighMass/plots_Bkg_e_2017.txt 3 LocalJob_sigstack_e_2017_unp2.out
./test/run_plots.sh test/sampleLists/signal_and_stack/POGTightID_unparametrized_LowAndHighMass/plots_Bkg_e_2018.txt 3 LocalJob_sigstack_e_2018_unp2.out
./test/run_plots.sh test/sampleLists/signal_and_stack/POGTightID_unparametrized_LowAndHighMass/plots_Bkg_m_2016.txt 3 LocalJob_sigstack_m_2016_unp2.out
./test/run_plots.sh test/sampleLists/signal_and_stack/POGTightID_unparametrized_LowAndHighMass/plots_Bkg_m_2017.txt 3 LocalJob_sigstack_m_2017_unp2.out
./test/run_plots.sh test/sampleLists/signal_and_stack/POGTightID_unparametrized_LowAndHighMass/plots_Bkg_m_2018.txt 3 LocalJob_sigstack_m_2018_unp2.out
